- name: ec2instace creation
  hosts: localhost
  tasks:
   - ec2:
      key_name: zenpublic
      instance_type: t2.micro
      image: ami-1d3c7472
      wait: yes
      group: webserver-sg
      count: 2
      vpc_subnet_id: subnet-d228879f
      assign_public_ip: yes 
      region: ap-south-1
     register: out

   - name: adding hosts to inventory
     add_host:
       hostname: "{{ item.private_ip }}"
       groupname: webservers
     with_items: "{{ out.instances }}"
     
   - name: Wait for SSH to come up
     wait_for:
      host: "{{ item.private_ip }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
     with_items: "{{ out.instances }}"    

- name: install webserver
  hosts: webservers
  tasks:
  - name: install webserver
    package:
      name: httpd
      state: installed

