- name: instance id
  hosts: all
  tasks:
  - name: ec2 instance
    ec2_instance_facts:
     filters:
      availability-zone: ap-south-1
    register: out

  - name: print
    debug:
      msg: "{{out}}"
