- hosts: all
  tasks:
  
  - name: replace file 80 to 8080
    lineinfile:
     path: /etc/httpd/conf/httpd.conf
     regexp: '^Listen 80'
     line: 'Listen 8080'
 
  - name: restart httpd
    service:
     name: httpd
     state: restarted
 
