- hosts: all
  tasks:

  - name: service httpd check
    yum:
     list: httpd
    register: pkg

  - name: printing output
    debug:
     msg: "{{pkg}}"
  
  - name: service restart
    service:
     name: httpd
     state: restarted
    when: pkg.results[1].yumstate == 'installed' 
