- hosts: all
  become: yes
  tasks:
  
  
  - name: this is priniting
    debug:
      msg: hello world
    tags: nagu

  - name: package installation
    package:
       name: httpd
       state: latest
 
