- hosts: all
  vars:
    secondname: sankar 
  vars_files: 
    - naguvar.yml
  tasks:

  - name: testing variables from file
    debug: 
     msg: "this is new varible form file {{firstname}} and second name is {{secondname}}"


